#pragma once

#include "esp_mac.h"
#include "esp_wifi.h"
#include "hal/gpio_types.h"

#pragma region Network

#define CONFIG_NETWORK_FALLBACK_TIMEOUT_SEC 10

#define CONFIG_ETHERNET_SPI_HOST 1
#define CONFIG_ETHERNET_SPI_CLOCK_MHZ 80

#define CONFIG_ETHERNET_SPI_PIN_CLK GPIO_NUM_12
#define CONFIG_ETHERNET_SPI_PIN_MOSI GPIO_NUM_11
#define CONFIG_ETHERNET_SPI_PIN_MISO GPIO_NUM_13
#define CONFIG_ETHERNET_SPI_PIN_CS GPIO_NUM_10
#define CONFIG_ETHERNET_SPI_PIN_INT GPIO_NUM_9
#define CONFIG_ETHERNET_SPI_PIN_RST GPIO_NUM_14

#define CONFIG_ETHERNET_MAC_ADDRESS ESP_MAC_WIFI_STA

#define CONFIG_WIFI_SSID "ssid"
#define CONFIG_WIFI_PASSPHRASE "pass"
#define CONFIG_WIFI_AUTHENTICATION WIFI_AUTH_WPA2_PSK
#define CONFIG_WIFI_RECONNECT_TIMEOUT_SEC 30

#pragma endregion Network

#pragma region HTTP

#define CONFIG_HTTP_SERVER_PORT 80

#define CONFIG_INDEX_TITLE "RCS"

#define CONFIG_ACTIONS_OPEN_URI "/actions/open"
#define CONFIG_ACTIONS_CLOSE_URI "/actions/close"
#define CONFIG_ACTIONS_STOP_URI "/actions/stop"

#define CONFIG_FLASH_URI "/flash"
#define CONFIG_FLASH_BUFFER_SIZE 4096

#pragma endregion HTTP

#pragma region Update

#define CONFIG_UPDATE_PARTITION_SIZE 0x3F0000

#pragma endregion Update

#pragma region Controller

#define CONFIG_CONTROLLER_CHANNEL_NUM 7

// Channel 0
#define CONFIG_CONTROLLER_CHANNEL0_ENABLE

#define CONFIG_CONTROLLER_CHANNEL0_INDEX 0
#define CONFIG_CONTROLLER_CHANNEL0_STOP_TIMEOUT_SEC 75

#define CONFIG_CONTROLLER_CHANNEL0_MOTOR_ENABLE GPIO_NUM_3
#define CONFIG_CONTROLLER_CHANNEL0_MOTOR_DIRECTION GPIO_NUM_4
#define CONFIG_CONTROLLER_CHANNEL0_MOTOR_INVERT 0

#define CONFIG_CONTROLLER_CHANNEL0_SWITCH_UP GPIO_NUM_1
#define CONFIG_CONTROLLER_CHANNEL0_SWITCH_DOWN GPIO_NUM_2
#define CONFIG_CONTROLLER_CHANNEL0_SWITCH_INVERT 0

// Channel 1
#define CONFIG_CONTROLLER_CHANNEL1_ENABLE

#define CONFIG_CONTROLLER_CHANNEL1_INDEX 1
#define CONFIG_CONTROLLER_CHANNEL1_STOP_TIMEOUT_SEC 75

#define CONFIG_CONTROLLER_CHANNEL1_MOTOR_ENABLE GPIO_NUM_7
#define CONFIG_CONTROLLER_CHANNEL1_MOTOR_DIRECTION GPIO_NUM_8
#define CONFIG_CONTROLLER_CHANNEL1_MOTOR_INVERT 0

#define CONFIG_CONTROLLER_CHANNEL1_SWITCH_UP GPIO_NUM_5
#define CONFIG_CONTROLLER_CHANNEL1_SWITCH_DOWN GPIO_NUM_6
#define CONFIG_CONTROLLER_CHANNEL1_SWITCH_INVERT 0

// Channel 2
#define CONFIG_CONTROLLER_CHANNEL2_ENABLE

#define CONFIG_CONTROLLER_CHANNEL2_INDEX 2
#define CONFIG_CONTROLLER_CHANNEL2_STOP_TIMEOUT_SEC 75

#define CONFIG_CONTROLLER_CHANNEL2_MOTOR_ENABLE GPIO_NUM_17
#define CONFIG_CONTROLLER_CHANNEL2_MOTOR_DIRECTION GPIO_NUM_18
#define CONFIG_CONTROLLER_CHANNEL2_MOTOR_INVERT 0

#define CONFIG_CONTROLLER_CHANNEL2_SWITCH_UP GPIO_NUM_15
#define CONFIG_CONTROLLER_CHANNEL2_SWITCH_DOWN GPIO_NUM_16
#define CONFIG_CONTROLLER_CHANNEL2_SWITCH_INVERT 0

// Channel 3
#define CONFIG_CONTROLLER_CHANNEL3_ENABLE

#define CONFIG_CONTROLLER_CHANNEL3_INDEX 3
#define CONFIG_CONTROLLER_CHANNEL3_STOP_TIMEOUT_SEC 75

#define CONFIG_CONTROLLER_CHANNEL3_MOTOR_ENABLE GPIO_NUM_47
#define CONFIG_CONTROLLER_CHANNEL3_MOTOR_DIRECTION GPIO_NUM_33
#define CONFIG_CONTROLLER_CHANNEL3_MOTOR_INVERT 0

#define CONFIG_CONTROLLER_CHANNEL3_SWITCH_UP GPIO_NUM_21
#define CONFIG_CONTROLLER_CHANNEL3_SWITCH_DOWN GPIO_NUM_26
#define CONFIG_CONTROLLER_CHANNEL3_SWITCH_INVERT 0

// Channel 4
#define CONFIG_CONTROLLER_CHANNEL4_ENABLE

#define CONFIG_CONTROLLER_CHANNEL4_INDEX 4
#define CONFIG_CONTROLLER_CHANNEL4_STOP_TIMEOUT_SEC 75

#define CONFIG_CONTROLLER_CHANNEL4_MOTOR_ENABLE GPIO_NUM_35
#define CONFIG_CONTROLLER_CHANNEL4_MOTOR_DIRECTION GPIO_NUM_36
#define CONFIG_CONTROLLER_CHANNEL4_MOTOR_INVERT 0

#define CONFIG_CONTROLLER_CHANNEL4_SWITCH_UP GPIO_NUM_34
#define CONFIG_CONTROLLER_CHANNEL4_SWITCH_DOWN GPIO_NUM_48
#define CONFIG_CONTROLLER_CHANNEL4_SWITCH_INVERT 0

// Channel 5
#define CONFIG_CONTROLLER_CHANNEL5_ENABLE

#define CONFIG_CONTROLLER_CHANNEL5_INDEX 5
#define CONFIG_CONTROLLER_CHANNEL5_STOP_TIMEOUT_SEC 75

#define CONFIG_CONTROLLER_CHANNEL5_MOTOR_ENABLE GPIO_NUM_39
#define CONFIG_CONTROLLER_CHANNEL5_MOTOR_DIRECTION GPIO_NUM_40
#define CONFIG_CONTROLLER_CHANNEL5_MOTOR_INVERT 0

#define CONFIG_CONTROLLER_CHANNEL5_SWITCH_UP GPIO_NUM_37
#define CONFIG_CONTROLLER_CHANNEL5_SWITCH_DOWN GPIO_NUM_38
#define CONFIG_CONTROLLER_CHANNEL5_SWITCH_INVERT 0

// Channel 6
#define CONFIG_CONTROLLER_CHANNEL6_ENABLE

#define CONFIG_CONTROLLER_CHANNEL6_INDEX 6
#define CONFIG_CONTROLLER_CHANNEL6_STOP_TIMEOUT_SEC 75

#define CONFIG_CONTROLLER_CHANNEL6_MOTOR_ENABLE GPIO_NUM_45
#define CONFIG_CONTROLLER_CHANNEL6_MOTOR_DIRECTION GPIO_NUM_46
#define CONFIG_CONTROLLER_CHANNEL6_MOTOR_INVERT 0

#define CONFIG_CONTROLLER_CHANNEL6_SWITCH_UP GPIO_NUM_41
#define CONFIG_CONTROLLER_CHANNEL6_SWITCH_DOWN GPIO_NUM_42
#define CONFIG_CONTROLLER_CHANNEL6_SWITCH_INVERT 0

// All Channels
#define CONFIG_CHANNEL_LOOP_STACK_SIZE 4096
#define CONFIG_CHANNEL_LOOP_TASK_PRIORITY 1
#define CONFIG_CHANNEL_LOOP_QUEUE_SIZE 10

#define CONFIG_CHANNEL_POLL_STACK_SIZE 2048
#define CONFIG_CHANNEL_POLL_TASK_PRIORITY 1

#define CONFIG_CHANNEL_MOTOR_ENABLE_OFF 0
#define CONFIG_CHANNEL_MOTOR_ENABLE_ON 1
#define CONFIG_CHANNEL_MOTOR_DIRECTION_OFF 0
#define CONFIG_CHANNEL_MOTOR_DIRECTION_ON 1

#define CONFIG_CHANNEL_MOTOR_RELAY_DELAY_MS 15
#define CONFIG_CHANNEL_MOTOR_REVERSING_DELAY_MS 500

#define CONFIG_CHANNEL_SWITCH_UP_OFF 1
#define CONFIG_CHANNEL_SWITCH_UP_ON 0
#define CONFIG_CHANNEL_SWITCH_DOWN_OFF 1
#define CONFIG_CHANNEL_SWITCH_DOWN_ON 0

#define CONFIG_CHANNEL_SWITCH_POLLING_DELAY_MS 50
#define CONFIG_CHANNEL_SWITCH_HOLD_DELAY_MS 250

#pragma endregion Controller
